### ISSUE TITLE
Support authenticationModes property in Account.java

### ISSUE THREAD

**Issue by cipous** [gooddata/gooddata-java#1056]
authenticationModes is supported when using JSON directly, but library does not have field.

**Comment by cipous** [comment]
I dont know how to link PR and issue, I dont have permissions? https://github.com/gooddata/gooddata-java/pull/1057

**Comment by peter-plochan** [comment]
@cipous just use e.g. word `fixes` (see [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
