### ISSUE TITLE
Create account with given login

### ISSUE THREAD

**Issue by cipous** [gooddata/gooddata-java#1070]
There is no way (constructor parameter or setter) how to create account with given login.

Please add possibility to create Account with login, possibly using constructor s one does not have to create constructor and then call several set methods.

**Comment by cipous** [comment]
Well, login is final, so it could be only via constructor.

**Comment by liry** [comment]
So the use case is the creation of account that has different login from email, right?

**Comment by cipous** [comment]
Yes, thats exactly what we need. We need to control login and we dont share it with user, he logs in through SSO and in case he will be removed from company SSO, he would not know the login and he cant reset password in GD directly.

**Comment by liry** [comment]
BTW, use also authenticationModes=SSO only if you don't want users to login using password ;)

**Comment by liry** [comment]
@cipous FYI: version 3.9.0+api3 is ready to be used: https://repo1.maven.org/maven2/com/gooddata/gooddata-java/3.9.0+api3/
https://github.com/gooddata/gooddata-java/releases/tag/gooddata-java-parent-3.9.0%2Bapi3
