### ISSUE TITLE
DataStoreService call fails with 500

### ISSUE THREAD

**Issue by martiner** [gooddata/gooddata-java#248]
If the call to WebDAV using DataStoreService is the first call to GoodData API (it doesn't contain the TT header), the request fails with HTTP error code 500.

I'm not sure whether it is a bug in GoodData WebDAV or the TT header is required, but it is a regression introduced by #213

GD: WA-6316

**Comment by pirkogdc** [comment]
* Acceptance test covering correct behaviour, as well as possible shortening of the expect delay is covered in https://github.com/martiner/gooddata-java/tree/jmi-webdavtimeout
* Added [Known limitations](https://github.com/martiner/gooddata-java/wiki/Known-limitations) with thorough description of the problem (till the issue on the server will be fixed)

**Comment by martiner** [comment]
Fixed on server side. We will leave the code in place for the case a regression should occur.
