### ISSUE TITLE
Provide ability to execute special dataload process "ADS to LDM synchronization"

### ISSUE THREAD

**Issue by vhtien** [gooddata/gooddata-java#297]
Need the way to execute special dataload process "ADS to LDM synchronization" which need to configure some datasets to synchronize

**Comment by martiner** [comment]
I updated the documentation https://github.com/gooddata/gooddata-java/wiki/Code-Examples#dataload-process-api but I'm not willing to extend `DATALOAD` processes support at the moment as there is literally no documentation at all.
