### ISSUE TITLE
executeReport could throw GoodDataRestException, code 500 when definition is not valid

### ISSUE THREAD

**Issue by jimirocks** [gooddata/gooddata-java#409]
Since the error handling and reporting in currently used `/gdc/xtab2/executor3` resource is far from ideal, the status 500 can be received even in certain cases when the problem is on user's side (i.e. invalid metric definition).

Let's investigate whether the newer resource `/gdc/www_internal/projects/{projectId}/execute` behaves better and/or consider  usage of more specific exception saying user it can be client error as well.

**Comment by martiner** [comment]
Moved to feature wishlist https://github.com/gooddata/gooddata-java/wiki/Ideas-for-future-improvements
