### ISSUE TITLE
Migrate to Java 8 Date Time API (instead of Joda-time)

### ISSUE THREAD

**Issue by To-da** [gooddata/gooddata-java#616]
**Why?**
Joda-time is not necessary when library is already compiled for Java 8. Moreover exposing Joda-time on API (like AbsoluteDateFilter) force consumers of this library to import Joda-time.

**How?**
Migrate to Java 8 Date Time API in whole Gooddata-java, remove Joda-time from dependencies and release it as next major version

**Comment by jimirocks** [comment]
Let's also consider introducing Java 8 dates fro current major version #617
