### ISSUE TITLE
Could AuditEventPageRequest be package private?

### ISSUE THREAD

**Issue by jimirocks** [gooddata/gooddata-java#710]

**Comment by peter-plochan** [comment]
This Java bean is used in our production code (Customer Facing Audit Log REST API). It represents special paging query parameters which can filter audit event type and time period of its occurrence.     
I recommend to move this bean to the `gooddata-java-model` library.

**Comment by peter-plochan** [comment]
As the [Paging](https://github.com/gooddata/gooddata-java/blob/3.0.0-RC/gooddata-java-model/src/main/java/com/gooddata/sdk/model/executeafm/result/Paging.java) is part of `gooddata-java-model`, we can move this bean to model as well.

**Comment by peter-plochan** [comment]
The bean (unlike `Paging`) is dependent on couple of spring libraries, so we have to even remove these dependencies or keep it in the service.
