### ISSUE TITLE
Introduce new Measure value filters

### ISSUE THREAD

**Issue by martinmosko** [gooddata/gooddata-java#853]
### Overview
Provide customers an option to filter entire insight (NOT measure) by the value of a measure in insight. This scope will only allow for filtering measures that are in the insight on granularity defined by attributes in the insight - you only get to filter values that you can see in the insight.

New filters are available for VisualizationObject and Afm instances.

### Breaking changes
- VisualizationObject filters property is using new interface `List<ExtendedFilter>` instead of `List<FilterItem>`
- AFM filters sources where moved to new sub-package `filter`

**Comment by peter-plochan** [comment]
Fixed
